version: "3.8"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    container_name: flask-backend
    ports:
      - "5000:5000"
    command: /bin/sh -c "sleep 10 && python create_tables.py && python etl.py && python app.py"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: talen168168
      POSTGRES_DB: Ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
